// Diccionario de traducciones
const translations = {
    es: {
        // SEO y Título del sitio
        "site_title": "AquaConecta - Conectando proveedores de agua con comunidades",

        // Navegación
        "nav_home": "Inicio",
        "nav_features": "Características",
        "nav_help": "A quienes ayudamos",
        "nav_problem": "Problemática",
        "nav_services": "Servicios",
        "nav_contact": "Contacto",
        "nav_team": "Equipo",

        // Hero Section
        "hero_title": "Conectando agua con quienes más la necesitan",
        "hero_description": "AquaConecta es una plataforma inteligente con tecnología IoT que revoluciona el acceso al agua potable, conectando proveedores con comunidades sin suministro constante, permitiendo monitorear en tiempo real la calidad y cantidad del agua disponible.",
        "hero_cta_download": "Descargar App",
        "hero_cta_more": "Más Información",

        // Features Section
        "features_title": "¿Por qué elegir AquaConecta?",
        "features_description": "Con AquaConecta, los usuarios pueden monitorear la calidad y cantidad de agua en sus hogares, mientras que los proveedores optimizan sus operaciones y mejoran la trazabilidad en la distribución.",
        "feature1_title": "Monitoreo en tiempo real",
        "feature1_description": "Supervisa la cantidad y calidad del agua disponible en tu hogar desde cualquier dispositivo con sensores IoT instalados en tus tanques.",
        "feature2_title": "Alertas inteligentes",
        "feature2_description": "Recibe notificaciones automáticas cuando el nivel de agua está bajo o si la calidad se ve comprometida.",
        "feature3_title": "Optimización de rutas",
        "feature3_description": "Los proveedores pueden coordinar eficientemente las entregas, priorizar zonas críticas y optimizar sus recorridos con datos en tiempo real.",
        "feature4_title": "Gestión de inventario",
        "feature4_description": "Control preciso del volumen disponible y planificación de la distribución basada en datos reales para una gestión más equitativa.",

        // Help Section
        "help_title": "A quienes queremos ayudar",
        "help_description": "Nuestra plataforma beneficia tanto a usuarios finales como a proveedores de agua",
        "help_users_title": "Para los usuarios",
        "help_users_description": "Toma el control de tu suministro de agua y mejora tu calidad de vida en zonas donde solo el 13.3% de los hogares cuentan con suministro continuo.",
        "help_users_benefit1": "Monitoreo en tiempo real de la cantidad y calidad del agua en tus tanques",
        "help_users_benefit2": "Alertas automáticas cuando el agua está por agotarse",
        "help_users_benefit3": "Programación y seguimiento de entregas de agua mediante camiones cisterna",
        "help_users_benefit4": "Información sobre la calidad del agua y prevención de riesgos sanitarios",
        "help_users_benefit5": "Planificación de consumo diario o semanal para un uso más eficiente",
        "help_providers_title": "Para los proveedores",
        "help_providers_description": "Optimiza tus operaciones y mejora la trazabilidad en la distribución de agua con nuestras herramientas especializadas basadas en IoT.",
        "help_providers_benefit1": "Planificación inteligente de rutas de distribución basada en datos reales",
        "help_providers_benefit2": "Monitoreo remoto del estado de tanques en múltiples hogares",
        "help_providers_benefit3": "Priorización automática de zonas críticas con bajo suministro",
        "help_providers_benefit4": "Panel de gestión con datos en tiempo real para toma de decisiones",
        "help_providers_benefit5": "Disponible en dos planes: básico (hasta 500 hogares) y avanzado (hasta 1,000 hogares)",

        // Problem Solution Section
        "problem_title": "La problemática del agua",
        "problem_description": "En regiones como Ica y Chincha, miles de familias enfrentan una grave crisis de acceso al agua potable",
        "problem_challenge_title": "El desafío actual",
        "problem_challenge1": "Solo el 13.3% de los hogares cuenta con suministro continuo durante 24 horas",
        "problem_challenge2": "Falta de trazabilidad y control por vivienda en la distribución",
        "problem_challenge3": "Riesgos en la calidad del agua distribuida por cisternas",
        "problem_challenge4": "Dependencia de métodos manuales sin datos en tiempo real",
        "problem_challenge5": "Problemas sanitarios por almacenamiento inadecuado",
        "solution_title": "Nuestra solución",
        "solution_description": "AquaConecta utiliza sensores IoT instalados en tanques domésticos para:",
        "solution1": "Monitorear en tiempo real niveles y calidad del agua",
        "solution2": "Transmitir datos a una plataforma accesible vía web y móvil",
        "solution3": "Permitir a usuarios visualizar su consumo y recibir alertas",
        "solution4": "Facilitar a proveedores optimizar rutas y priorizar zonas críticas",
        "solution5": "Reducir riesgos sanitarios y mejorar la distribución equitativa",

        // Services Section
        "services_title": "Nuestros Servicios",
        "services_description": "Conoce los planes y servicios que ofrecemos para garantizar tu acceso al agua",
        "service_main_title": "Plan Agua Segura",
        "service_price_info": "por cada sensor",
        "service_main_description": "Sabes cuánta agua tienes y si está limpia, todo desde tu celular.",
        "service_feature1": "El sensor",
        "service_feature2": "Instalación con técnico",
        "service_feature3": "1 mes de uso del sistema",
        "service_feature4": "Luego solo pagas S/ 50 al mes por sensor activo",
        "service_benefit1": "Ver nivel y calidad del agua",
        "service_benefit2": "Recibir alertas",
        "service_benefit3": "Acceso desde el celular",
        "service_cta": "Solicitar Plan",
        "service_maintenance_title": "Mantenimiento",
        "service_maintenance_description": "Servicio técnico especializado para garantizar el correcto funcionamiento de tus sensores.",
        "service_consult": "Consultar",
        "service_business_title": "Plan Empresarial",
        "service_business_description": "Soluciones personalizadas para negocios, industrias y edificios multifamiliares.",
        "service_more_info": "Más información",
        "service_advice_title": "Asesoría",
        "service_advice_description": "Aprende a optimizar tu consumo de agua y reducir costos con nuestros especialistas.",
        "service_schedule": "Agendar cita",
        "service_info_title": "¿Necesitas más información?",
        "service_info_description": "Nuestro equipo está listo para ayudarte a elegir el plan que mejor se adapte a tus necesidades.",
        "service_contact_us": "Contacta con nosotros",

        // Contact Section
        "contact_title": "Contacta con nosotros",
        "contact_description": "¿Tienes preguntas o sugerencias? Estamos aquí para ayudarte",
        "contact_name": "Nombre",
        "contact_email": "Correo electrónico",
        "contact_subject": "Asunto",
        "contact_subject_info": "Información general",
        "contact_subject_support": "Soporte técnico",
        "contact_subject_partnership": "Colaboración",
        "contact_subject_other": "Otro",
        "contact_message": "Mensaje",
        "contact_send": "Enviar mensaje",
        "contact_address_title": "Dirección",
        "contact_address": "Av. Tecnológica 1234, Ciudad Innovación",
        "contact_phone_title": "Teléfono",
        "contact_email_title": "Email",
        "contact_download_title": "Descarga AquaConecta",
        "contact_download_description": "Disponible para iOS y Android",
        "download_on": "Descarga en",
        "available_on": "Disponible en",

        // Footer
        "footer_tagline": "Conectando agua con quienes más la necesitan",
        "footer_quick_links": "Enlaces rápidos",
        "footer_resources": "Recursos",
        "footer_faq": "Preguntas frecuentes",
        "footer_blog": "Blog",
        "footer_tutorials": "Tutoriales",
        "footer_help_center": "Centro de ayuda",
        "footer_legal": "Legal",
        "footer_terms": "Términos de servicio",
        "footer_privacy": "Política de privacidad",
        "footer_cookies": "Cookies",
        "footer_copyright": "© 2025 AquaConecta. Todos los derechos reservados.",
        "footer_tagline_extended": "Diseñado con ♥ para comunidades con acceso limitado al agua",

        // Team Section
        "team_title": "Nuestro Equipo",
        "team_description": "Conozca al equipo de ingenieros de software detrás de AquaConecta",
        "team_about_us": "Sobre Nosotros",
        "team_intro": "Somos un equipo de ingenieros de software comprometidos con la innovación y el desarrollo de soluciones tecnológicas que mejoren el acceso al agua potable.",

    },

    en: {
        // SEO and Site Title
        "site_title": "AquaConecta - Connecting water providers with communities",

        // Navigation
        "nav_home": "Home",
        "nav_features": "Features",
        "nav_help": "Who We Help",
        "nav_problem": "Problem",
        "nav_services": "Services",
        "nav_contact": "Contact",
        "nav_team": "Team",

        // Hero Section
        "hero_title": "Connecting water with those who need it most",
        "hero_description": "AquaConecta is a smart platform with IoT technology that revolutionizes access to drinking water, connecting providers with communities without constant supply, allowing real-time monitoring of the quality and quantity of available water.",
        "hero_cta_download": "Download App",
        "hero_cta_more": "More Information",

        // Features Section
        "features_title": "Why choose AquaConecta?",
        "features_description": "With AquaConecta, users can monitor the quality and quantity of water in their homes, while providers optimize their operations and improve traceability in distribution.",
        "feature1_title": "Real-time monitoring",
        "feature1_description": "Monitor the quantity and quality of water available in your home from any device with IoT sensors installed in your tanks.",
        "feature2_title": "Smart alerts",
        "feature2_description": "Receive automatic notifications when the water level is low or if the quality is compromised.",
        "feature3_title": "Route optimization",
        "feature3_description": "Providers can efficiently coordinate deliveries, prioritize critical areas, and optimize their routes with real-time data.",
        "feature4_title": "Inventory management",
        "feature4_description": "Precise control of available volume and planning of distribution based on real data for more equitable management.",

        // Help Section
        "help_title": "Who We Want to Help",
        "help_description": "Our platform benefits both end users and water providers",
        "help_users_title": "For users",
        "help_users_description": "Take control of your water supply and improve your quality of life in areas where only 13.3% of households have continuous supply.",
        "help_users_benefit1": "Real-time monitoring of the quantity and quality of water in your tanks",
        "help_users_benefit2": "Automatic alerts when water is about to run out",
        "help_users_benefit3": "Scheduling and tracking of water deliveries by tanker trucks",
        "help_users_benefit4": "Information on water quality and prevention of health risks",
        "help_users_benefit5": "Planning daily or weekly consumption for more efficient use",
        "help_providers_title": "For providers",
        "help_providers_description": "Optimize your operations and improve traceability in water distribution with our specialized IoT-based tools.",
        "help_providers_benefit1": "Intelligent planning of distribution routes based on real data",
        "help_providers_benefit2": "Remote monitoring of tank status in multiple homes",
        "help_providers_benefit3": "Automatic prioritization of critical areas with low supply",
        "help_providers_benefit4": "Management dashboard with real-time data for decision making",
        "help_providers_benefit5": "Available in two plans: basic (up to 500 homes) and advanced (up to 1,000 homes)",

        // Problem Solution Section
        "problem_title": "The water problem",
        "problem_description": "In regions like Ica and Chincha, thousands of families face a serious crisis in access to drinking water",
        "problem_challenge_title": "The current challenge",
        "problem_challenge1": "Only 13.3% of households have continuous supply for 24 hours",
        "problem_challenge2": "Lack of traceability and control per household in distribution",
        "problem_challenge3": "Risks in the quality of water distributed by tankers",
        "problem_challenge4": "Dependence on manual methods without real-time data",
        "problem_challenge5": "Health problems due to inadequate storage",
        "solution_title": "Our solution",
        "solution_description": "AquaConecta uses IoT sensors installed in domestic tanks to:",
        "solution1": "Monitor water levels and quality in real-time",
        "solution2": "Transmit data to a platform accessible via web and mobile",
        "solution3": "Allow users to visualize their consumption and receive alerts",
        "solution4": "Help providers optimize routes and prioritize critical areas",
        "solution5": "Reduce health risks and improve equitable distribution",

        // Services Section
        "services_title": "Our Services",
        "services_description": "Learn about the plans and services we offer to guarantee your access to water",
        "service_main_title": "Safe Water Plan",
        "service_price_info": "per sensor",
        "service_main_description": "Know how much water you have and if it's clean, all from your phone.",
        "service_feature1": "The sensor",
        "service_feature2": "Installation with technician",
        "service_feature3": "1 month of system use",
        "service_feature4": "Then you only pay S/ 50 per month per active sensor",
        "service_benefit1": "View water level and quality",
        "service_benefit2": "Receive alerts",
        "service_benefit3": "Access from your phone",
        "service_cta": "Request Plan",
        "service_maintenance_title": "Maintenance",
        "service_maintenance_description": "Specialized technical service to ensure the proper functioning of your sensors.",
        "service_consult": "Consult",
        "service_business_title": "Business Plan",
        "service_business_description": "Customized solutions for businesses, industries, and multi-family buildings.",
        "service_more_info": "More information",
        "service_advice_title": "Advisory",
        "service_advice_description": "Learn to optimize your water consumption and reduce costs with our specialists.",
        "service_schedule": "Schedule appointment",
        "service_info_title": "Need more information?",
        "service_info_description": "Our team is ready to help you choose the plan that best suits your needs.",
        "service_contact_us": "Contact us",

        // Contact Section
        "contact_title": "Contact us",
        "contact_description": "Have questions or suggestions? We're here to help",
        "contact_name": "Name",
        "contact_email": "Email",
        "contact_subject": "Subject",
        "contact_subject_info": "General information",
        "contact_subject_support": "Technical support",
        "contact_subject_partnership": "Partnership",
        "contact_subject_other": "Other",
        "contact_message": "Message",
        "contact_send": "Send message",
        "contact_address_title": "Address",
        "contact_address": "Av. Tecnológica 1234, Innovation City",
        "contact_phone_title": "Phone",
        "contact_email_title": "Email",
        "contact_download_title": "Download AquaConecta",
        "contact_download_description": "Available for iOS and Android",
        "download_on": "Download on",
        "available_on": "Available on",

        // Footer
        "footer_tagline": "Connecting water with those who need it most",
        "footer_quick_links": "Quick links",
        "footer_resources": "Resources",
        "footer_faq": "FAQ",
        "footer_blog": "Blog",
        "footer_tutorials": "Tutorials",
        "footer_help_center": "Help center",
        "footer_legal": "Legal",
        "footer_terms": "Terms of service",
        "footer_privacy": "Privacy policy",
        "footer_cookies": "Cookies",
        "footer_copyright": "© 2025 AquaConecta. All rights reserved.",
        "footer_tagline_extended": "Designed with ♥ for communities with limited access to water",

        // Para inglés (dentro del objeto 'en')
        "team_title": "Our Team",
        "team_description": "Meet the software engineering team behind AquaConecta",
        "team_about_us": "About Us",
        "team_intro": "We are a team of software engineers committed to innovation and the development of technological solutions that improve access to drinking water.",
    }


};